### ISSUE TITLE
failed to execute demo in sgx hw mode

### ISSUE THREAD

**Issue by wangsu502** [mc2-project/secure-xgboost#125]
~/secure-xgboost/demo/python/basic$ python3 secure-xgboost-demo.py
Init user and enclave parameters
Remote attestation
2020-10-27T05:33:37.000000Z [(H)ERROR] tid(0x7f897ef07740) | quote3_error_t=0xe044
 (oe_result_t=OE_PLATFORM_ERROR) [/source/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:21]
2020-10-27T05:33:37.000000Z [(H)ERROR] tid(0x7f897ef07740) | :OE_PLATFORM_ERROR [/source/host/sgx/quote.c:sgx_get_qetarget_info:31]
2020-10-27T05:33:37.000000Z [(H)ERROR] tid(0x7f897ef07740) | :OE_ENCLAVE_ABORTING [/source/host/calls.c:oe_call_enclave_function_by_table_id:91]
Ecall failed: result=19 (OE_ENCLAVE_ABORTING)
Traceback (most recent call last):
  File "secure-xgboost-demo.py", line 17, in <module>
    xgb.attest(False)
  File "/usr/local/lib/python3.6/dist-packages/securexgboost-0.1-py3.6.egg/securexgboost/core.py", line 2652, in attest
    ctypes.byref(remote_report), ctypes.byref(remote_report_size)))
  File "/usr/local/lib/python3.6/dist-packages/securexgboost-0.1-py3.6.egg/securexgboost/core.py", line 203, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
securexgboost.core.XGBoostError

**Comment by podcastinator** [comment]
Are you running the code on a machine that does not have SGX support? If so, then you  would need to build and run the code in simulation mode instead. Please confirm?

**Comment by wangsu502** [comment]
> Are you running the code on a machine that does not have SGX support? If so, then you would need to build and run the code in simulation mode instead. Please confirm?

Hi, I'm using a sgx-enabled i7 machine, and I fixed the problem by reinstall the sgx driver :)

**Comment by podcastinator** [comment]
Ah, great. Closing this issue for now then!
